import { RoomConnectionState } from "@whereby.com/core";

export const initialState: RoomConnectionState = {
    chatMessages: [],
    fileUploads: [],
    cloudRecording: undefined,
    breakout: {
        isAvailable: false,
        error: null,
        isActive: false,
        currentGroup: null,
        groups: null,
        enforceAssignment: false,
        autoMoveToGroup: false,
        moveToGroupGracePeriod: null,
        autoMoveToMain: false,
        moveToMainGracePeriod: null,
        breakoutTimerSetting: false,
        breakoutTimerDuration: 0,
        startedAt: null,
        endTime: null,
        moveToGroupAt: null,
        moveToMainAt: null,
        groupedParticipants: [],
        participantsInCurrentGroup: [],
        broadcastingParticipants: [],
    },
    isCameraEnabled: false,
    isMicrophoneEnabled: false,
    localParticipant: undefined,
    remoteParticipants: [],
    roomIntegrations: {
        hasFetched: false,
        isFetching: false,
        error: null,
        embeddable: [],
        enabled: [],
        running: [],
    },
    screenshares: [],
    connectionStatus: "ready",
    connectionError: null,
    knockResponse: null,
    waitingParticipants: [],
    spotlightedParticipants: [],
};
