import { RoomConnectionState } from "@whereby.com/core";

export const initialState: RoomConnectionState = {
    chatMessages: [],
    fileUploads: [],
    cloudRecording: undefined,
    breakout: {
        isActive: false,
        currentGroup: null,
        groups: null,
        enforceAssignment: false,
        autoMoveToGroup: false,
        moveToGroupGracePeriod: null,
        autoMoveToMain: false,
        moveToMainGracePeriod: null,
        breakoutTimerSetting: false,
        breakoutTimerDuration: 0,
        startedAt: null,
        endTime: null,
        moveToGroupAt: null,
        moveToMainAt: null,
        groupedParticipants: [],
        participantsInCurrentGroup: [],
        broadcastingParticipants: [],
    },
    isCameraEnabled: false,
    isMicrophoneEnabled: false,
    localParticipant: undefined,
    remoteParticipants: [],
    screenshares: [],
    connectionStatus: "ready",
    connectionError: null,
    waitingParticipants: [],
    spotlightedParticipants: [],
};
