import { createSelector } from "@reduxjs/toolkit";
import {
    selectLocalParticipantRaw,
    selectChatMessages,
    selectFileUploads,
    selectCloudRecordingRaw,
    selectRemoteParticipants,
    selectScreenshares,
    selectRoomConnectionStatus,
    selectRoomConnectionKnockResponse,
    selectWaitingParticipants,
    selectLiveTranscriptionRaw,
    selectLocalMediaStream,
    selectStreamingRaw,
    selectNotificationsEmitter,
    selectSpotlightedClientViews,
    selectBreakoutCurrentGroup,
    selectBreakoutCurrentId,
    selectBreakoutActive,
    selectBreakoutGroupedParticipants,
    selectBreakoutGroups,
    selectBreakoutAssignments,
    selectBreakoutEnforceAssignment,
    selectBreakoutTimerSetting,
    selectBreakoutTimerDuration,
    selectBreakoutAutoMoveToGroup,
    selectBreakoutMoveToGroupGracePeriod,
    selectBreakoutAutoMoveToMain,
    selectBreakoutMoveToMainGracePeriod,
    selectBreakoutStartedAt,
    selectBreakoutEndTime,
    selectBreakoutMoveToGroupAt,
    selectBreakoutMoveToMainAt,
    selectBreakoutIsAvailable,
    selectBreakoutError,
    selectAllClientViewsInCurrentGroup,
    selectRoomConnectionError,
    selectIsCameraEnabled,
    selectIsMicrophoneEnabled,
    selectLiveCaptionsRaw,
    selectRoomIntegrationsRaw,
    selectEnabledRoomIntegrations,
    selectEmbeddableRoomIntegrations,
    selectRunningRoomIntegrations,
} from "../../redux";

import { RoomConnectionState } from "./types";

export const selectRoomConnectionState = createSelector(
    selectChatMessages,
    selectFileUploads,
    selectCloudRecordingRaw,
    selectBreakoutCurrentGroup,
    selectBreakoutCurrentId,
    selectBreakoutActive,
    selectBreakoutGroupedParticipants,
    selectBreakoutGroups,
    selectBreakoutAssignments,
    selectBreakoutEnforceAssignment,
    selectBreakoutTimerSetting,
    selectBreakoutTimerDuration,
    selectBreakoutAutoMoveToGroup,
    selectBreakoutMoveToGroupGracePeriod,
    selectBreakoutAutoMoveToMain,
    selectBreakoutMoveToMainGracePeriod,
    selectBreakoutStartedAt,
    selectBreakoutEndTime,
    selectBreakoutMoveToGroupAt,
    selectBreakoutMoveToMainAt,
    selectBreakoutIsAvailable,
    selectBreakoutError,
    selectAllClientViewsInCurrentGroup,
    selectLiveCaptionsRaw,
    selectLiveTranscriptionRaw,
    selectLocalParticipantRaw,
    selectLocalMediaStream,
    selectRemoteParticipants,
    selectScreenshares,
    selectRoomConnectionStatus,
    selectRoomConnectionError,
    selectRoomConnectionKnockResponse,
    selectStreamingRaw,
    selectWaitingParticipants,
    selectNotificationsEmitter,
    selectSpotlightedClientViews,
    selectIsCameraEnabled,
    selectIsMicrophoneEnabled,
    selectRoomIntegrationsRaw,
    selectEnabledRoomIntegrations,
    selectEmbeddableRoomIntegrations,
    selectRunningRoomIntegrations,
    (
        chatMessages,
        fileUploads,
        cloudRecording,
        breakoutCurrentGroup,
        breakoutCurrentId,
        breakoutActive,
        breakoutGroupedParticipants,
        breakoutGroups,
        breakoutAssignments,
        breakoutEnforceAssignment,
        breakoutTimerSetting,
        breakoutTimerDuration,
        breakoutAutoMoveToGroup,
        breakoutMoveToGroupGracePeriod,
        breakoutAutoMoveToMain,
        breakoutMoveToMainGracePeriod,
        breakoutStartedAt,
        breakoutEndTime,
        breakoutMoveToGroupAt,
        breakoutMoveToMainAt,
        breakoutIsAvailable,
        breakoutError,
        clientViewsInCurrentGroup,
        liveCaptions,
        liveTranscription,
        localParticipant,
        localMediaStream,
        remoteParticipants,
        screenshares,
        connectionStatus,
        connectionError,
        knockResponse,
        streaming,
        waitingParticipants,
        notificationsEmitter,
        spotlightedClientViews,
        isCameraEnabled,
        isMicrophoneEnabled,
        roomIntegrationsRaw,
        enabledRoomIntegrations,
        embeddableRoomIntegrations,
        runningRoomIntegrations,
    ) => {
        // Main-room participants that are spotlighted broadcast their audio/video into every group.
        // Only relevant for participants who are currently inside a group.
        const broadcastingParticipants =
            breakoutActive && breakoutCurrentId
                ? spotlightedClientViews.filter((c) => !c.breakoutGroup && c.isAudioEnabled && !c.isPresentation)
                : [];

        const state: RoomConnectionState = {
            chatMessages,
            fileUploads,
            cloudRecording: cloudRecording.status
                ? {
                      error: cloudRecording.error,
                      startedAt: cloudRecording.startedAt,
                      status: cloudRecording.status,
                  }
                : undefined,
            breakout: {
                isAvailable: breakoutIsAvailable,
                error: breakoutError,
                isActive: breakoutActive,
                currentGroup: breakoutCurrentGroup,
                groups: breakoutGroups ?? null,
                enforceAssignment: breakoutEnforceAssignment ?? false,
                autoMoveToGroup: breakoutAutoMoveToGroup ?? false,
                moveToGroupGracePeriod: breakoutMoveToGroupGracePeriod ?? null,
                autoMoveToMain: breakoutAutoMoveToMain ?? false,
                moveToMainGracePeriod: breakoutMoveToMainGracePeriod ?? null,
                breakoutTimerSetting: breakoutTimerSetting ?? false,
                breakoutTimerDuration: breakoutTimerDuration ?? 0,
                startedAt: breakoutStartedAt ?? null,
                endTime: breakoutEndTime,
                moveToGroupAt: breakoutMoveToGroupAt,
                moveToMainAt: breakoutMoveToMainAt,
                groupedParticipants: breakoutGroupedParticipants,
                participantsInCurrentGroup: clientViewsInCurrentGroup,
                broadcastingParticipants,
            },
            connectionStatus,
            connectionError,
            knockResponse,
            events: notificationsEmitter,
            isCameraEnabled,
            isMicrophoneEnabled,
            liveStream: streaming.isStreaming
                ? {
                      status: "streaming",
                      startedAt: streaming.startedAt,
                  }
                : undefined,
            liveCaptions: liveCaptions.status
                ? {
                      error: liveCaptions.error,
                      startedAt: liveCaptions.startedAt,
                      status: liveCaptions.status,
                      captionLog: liveCaptions.captionLog,
                  }
                : undefined,
            liveTranscription: liveTranscription.status
                ? {
                      error: liveTranscription.error,
                      startedAt: liveTranscription.startedAt,
                      status: liveTranscription.status,
                  }
                : undefined,
            localScreenshareStatus: localParticipant.isScreenSharing ? "active" : undefined,
            localParticipant: { ...localParticipant, stream: localMediaStream },
            remoteParticipants: remoteParticipants.map((participant) => ({
                ...participant,
                breakoutGroupAssigned: breakoutAssignments?.[participant.deviceId] || "",
            })),
            roomIntegrations: {
                hasFetched: roomIntegrationsRaw.hasFetched,
                isFetching: roomIntegrationsRaw.isFetching,
                error: roomIntegrationsRaw.error,
                embeddable: embeddableRoomIntegrations,
                enabled: enabledRoomIntegrations,
                running: runningRoomIntegrations,
            },
            screenshares,
            waitingParticipants,
            spotlightedParticipants: spotlightedClientViews,
        };

        return state;
    },
);
