name: "Slack Notification"
description: "Send a slack notification when package(s) are published"
inputs:
    channel_id:
        description: "The slack channel to send the message to"
        required: true
    slack_bot_token:
        description: "The slack bot token"
        required: true
    published_packages:
        description: "Stringified JSON of the published packages"
        required: true
runs:
    using: "composite"
    steps:
        - name: Get published packages
          id: get-published-packages
          shell: bash
          env:
              JSON: ${{ inputs.published_packages }}
          run: |
              PACKAGES=$(echo "$JSON" | jq -r 'map(.name + "@" + .version) | join("\n")')
              echo "packages=$PACKAGES" >> $GITHUB_OUTPUT

        - name: Send slack message
          id: slack
          uses: slackapi/slack-github-action@v1.25.0
          with:
              channel-id: ${{ inputs.channel_id }}
              payload: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "SDK: Publish to npm and deploy CDN build completed"
                        }
                      },
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Status:*\nCompleted"
                          },
                          {
                            "type": "mrkdwn",
                            "text": "*Packages:*\n${{ steps.get-published-packages.outputs.packages }}"
                          }
                        ]
                      }
                    ]
                  }
          env:
              SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
